average: var
batch_size: 64
cond_modes: 4
cov_diagonal: var
cov_off_diagonal: ''
device: cuda
eps: 0.001
eval_batch_size: 1024
ff_activation: relu
ff_dim_hidden: 0
ff_layer_norm: true
ff_layers: 2
ff_residual_connection: false
init_std: 0.01
lr: 0.001
marg_modes: 1
margin_lr: 0.001
n_epochs: 10
n_epochs_marg: 5
n_epochs_stop: 1
optimize_mu: true
stopping_criterion: max_epochs
use_tanh: true
